MANUFACTURER_ID = [0x41]  # Roland
GT1000_FAMILY = [0x4F, 0x03]
DEVICE_ID_TMP = [0xFF]  # this gets overwritten by gt1000.device_id
MODEL_ID = [0x00, 0x00, 0x00, 0x4F]
COMMAND_ID = [0x12]
SYSEX_HEADER = MANUFACTURER_ID + DEVICE_ID_TMP + MODEL_ID + COMMAND_ID

SYSEX_START = [0xF0]
SYSEX_END = [0xF7]

NON_RT_MSG = [0x7E]
BCAST_DEV_ID = [0x7F]
GEN_INFO = [0x06]
IDENTITY_REQUEST = [0x01]
IDENTITY_REPLY = [0x02]

IDENTITY_REQUEST_MSG = (
    SYSEX_START + NON_RT_MSG + BCAST_DEV_ID + GEN_INFO + IDENTITY_REQUEST + SYSEX_END
)
